INHERIT: ./mkdocs_base.yml

site_name: 基础平台 # Change this to your site name
site_description: 基础平台

plugins:
    awesome-pages:
        filename: .pages
    exclude:
        glob:
#        - 架构设计/基础平台2.0*
            - '架构设计/[!{基础平台2.0}]*'
            - 需求分析/*
            - 数据库设计/*
            - 接口设计/[!{i}]*
            - 概要设计/[!{i}]*
        regex:
            - '^(?!.*基础平台2\.0).*\.md$'
